### ISSUE TITLE
Serve other formats

### ISSUE THREAD

**Issue by markuman** [uktrade/mbtiles-s3-server#3]
tileserver-gl can serve .pbf, .png, .jpg and .webp.   
For example: https://maps.osuv.de/styles/osm-bright/{z}/{x}/{y}@2x.png

With this notation, the tileserver can be easily used in other applications. E.g. nextcloud  gpxpod, gpxedit and gpxmotion.

![Screenshot from 2022-07-12 08-36-16](https://user-images.githubusercontent.com/3920157/178425066-83ddd39f-f776-48d1-9c3d-87f03c89edb2.png)

**Comment by michalc** [comment]
Sounds (mostly*) reasonable... do you know if the server is expected to convert from vector tiles to the other formats on the fly? Or are the png files etc expected to be in the mbtiles file?

*The mostly: I'm a bit scared of scope creep - so far this is a vector file server. If it won't make things much more complicated, or add too many more dependencies etc etc, then probably all good, but otherwise, I'm not sure...

**Comment by markuman** [comment]
> do you know if the server is expected to convert from vector tiles to the other formats on the fly? 

afaik, yes. on the fly

> *The mostly: I'm a bit scared of scope creep - so far this is a vector file server. If it won't make things much more complicated, or add too many more dependencies etc etc, then probably all good, but otherwise, I'm not sure...

I fully understand, it's tiny and fast and you can serve the entire world with just 5$/month now.  
When I start serving my own tiles, it took 2 month to generate the tiles...

mbtiles-s3-server and https://github.com/onthegomap/planetiler are together a game-changer.

**Comment by markuman** [comment]
To be clear

>  .pbf, .png, .jpg and .webp.

only one _image_ format would be sufficient, even svg.   
Or if there is a conversation of `{z}/{x}/{y}` that directs to `https://osm.osuv.de/v1/tiles/mytiles@1.0.0/14/7341/10373.mvt` so that a different service can made the conversation....  
I know python, but sadly I've no experiences in osm & image processing.

**Comment by michalc** [comment]
Can you explain the different service thing? Other services should be able to use the vector tiles served already I think? (At least if they’re told the structure of the urls)

**Comment by michalc** [comment]
I've been pondering this more, and I think I'm going to have to be a bit ruthless, and say no to the supporting of other image formats, especially if on-the-fly conversion is involved. I think you summed it up really well:

> it's tiny and fast and you can serve the entire world with just 5$/month now.

So it sounds pretty good now, and I'm even hoping we can make it an even better vector map tile server as time goes on, and so certainly happy to look into issues raised on serving such tiles (e.g. like your other issues you raised - thank you for those btw).

But I think that adding format conversion functionality has too high a chance of effectively making this a worse vector tile server:

- such conversions would probably need more dependencies, so a higher chance of security issues
- and we would have a higher API surface area, and so also a higher chance of security issues
- I think it would harder to optimise, performance-wise - suspect such conversions have different performance characteristics (right now the sever is event-loop based since nothing is that CPU intensive AFAIK - might not be the case any more with on-the-fly conversions)
- and if nothing else we'd end up spending time that otherwise could be spent improving this as a vector tile server

I would probably go as far as saying that we probably wouldn't even accept PRs that added such functionality (unless they seemed _very_ straightforward - I'm no image processing expert either).

So I am going to close this issue

(Although I am still curious as to making it easier for other services/applications to consume the vector tiles from this server - that feels fairly "in scope" of this project to me)
